#spring.application.name=demo
spring.application.name=productapp
server.port=8080

#
## H2 setup
##spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.url=jdbc:h2:file:./data/demo
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.h2.console.enabled=true
#
## hibernate setup
##Testing
##spring.jpa.hibernate.ddl-auto = create-drop
##Developement
#spring.jpa.hibernate.ddl-auto = update
##spring.jpa.hibernate.ddl-auto = validate
##spring.jpa.hibernate.ddl-auto = none
##spring.jpa.open-in-view = false
## Server Port
#server.port=8080
#
#
#
##spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true


spring.cloud.gcp.project-id=cybernetic-pact-417810

spring.cloud.gcp.sql.enabled=true
spring.cloud.gcp.sql.instance-connection-name= cybernetic-pact-417810:asia-south1:gayathri-postgres
spring.cloud.gcp.sql.database-name= postgresdevdb
spring.datasource.username= gayathri-devdbpostgres
spring.datasource.password= Z}T[b.{{)@8,l0gE

# Optional: use PRIVATE for a private-IP Cloud SQL instance
spring.cloud.gcp.sql.ip-types=PUBLIC

# For initial development only
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true